// Code generated by MockGen. DO NOT EDIT.
// Source: image.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"

	model "github.com/tusmasoma/campfinder/docker/back/domain/model"
)

// MockImageUseCase is a mock of ImageUseCase interface.
type MockImageUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockImageUseCaseMockRecorder
}

// MockImageUseCaseMockRecorder is the mock recorder for MockImageUseCase.
type MockImageUseCaseMockRecorder struct {
	mock *MockImageUseCase
}

// NewMockImageUseCase creates a new mock instance.
func NewMockImageUseCase(ctrl *gomock.Controller) *MockImageUseCase {
	mock := &MockImageUseCase{ctrl: ctrl}
	mock.recorder = &MockImageUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageUseCase) EXPECT() *MockImageUseCaseMockRecorder {
	return m.recorder
}

// CreateImage mocks base method.
func (m *MockImageUseCase) CreateImage(ctx context.Context, spotID uuid.UUID, url string, user model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImage", ctx, spotID, url, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateImage indicates an expected call of CreateImage.
func (mr *MockImageUseCaseMockRecorder) CreateImage(ctx, spotID, url, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImage", reflect.TypeOf((*MockImageUseCase)(nil).CreateImage), ctx, spotID, url, user)
}

// DeleteImage mocks base method.
func (m *MockImageUseCase) DeleteImage(ctx context.Context, id, userID string, user model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, id, userID, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockImageUseCaseMockRecorder) DeleteImage(ctx, id, userID, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockImageUseCase)(nil).DeleteImage), ctx, id, userID, user)
}

// ListSpotImgURLs mocks base method.
func (m *MockImageUseCase) ListSpotImgURLs(ctx context.Context, spotID string) ([]model.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSpotImgURLs", ctx, spotID)
	ret0, _ := ret[0].([]model.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSpotImgURLs indicates an expected call of ListSpotImgURLs.
func (mr *MockImageUseCaseMockRecorder) ListSpotImgURLs(ctx, spotID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSpotImgURLs", reflect.TypeOf((*MockImageUseCase)(nil).ListSpotImgURLs), ctx, spotID)
}
