version: "3"

services:
  redis:
    container_name: campfinder_redis
    image: redis:5.0
    ports:
      - 6379:6379

  mysql:
    container_name: campfinder_db
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  back:
    container_name: campfinder_back
    build:
      context: ./
      dockerfile: ./docker/back/Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      - redis
      - mysql

  nginx:
    container_name: campfinder_nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - back

volumes:
  db-data:
    driver: local
