version: "3"

services:
  back:
    container_name: campfinder_back
    build:
      context: ./
      dockerfile: ./docker/back/Dockerfile.production
    ports:
      - "8083:8083"
    env_file:
      - .env

  nginx:
    container_name: campfinder_nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    #depends_on:
    #  - back
