CREATE DATABASE IF NOT EXISTS `campfinderdb` DEFAULT CHARACTER SET utf8mb4 ;
USE `campfinderdb` ;

DROP TABLE IF EXISTS User CASCADE;
DROP TABLE IF EXISTS Spot CASCADE;
DROP TABLE IF EXISTS Comment CASCADE;
DROP TABLE IF EXISTS Image CASCADE;

CREATE TABLE User (
    id CHAR(36) PRIMARY KEY, -- UUIDは36文字の文字列として格納されます
    name VARCHAR(50) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,  -- 暗号化されたパスワードを格納
    is_admin BOOLEAN DEFAULT FALSE
);

CREATE TABLE Spot (
    id CHAR(36) PRIMARY KEY, -- UUIDは36文字の文字列として格納されます
    category VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    period VARCHAR(150) DEFAULT '-',
    phone VARCHAR(100) DEFAULT '-',
    price VARCHAR(400) DEFAULT '-',
    description TEXT ,
    iconpath VARCHAR(30) DEFAULT 'iconpath'
);

CREATE TABLE Comment (
    id CHAR(36) PRIMARY KEY, -- UUIDは36文字の文字列として格納されます
    spot_id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    star_rate DECIMAL(2,1) NOT NULL,
    text TEXT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (spot_id) REFERENCES Spot(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE Image (
    id CHAR(36) PRIMARY KEY, -- UUIDは36文字の文字列として格納されます
    spot_id CHAR(36) NOT NULL,
    url VARCHAR(255) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (spot_id) REFERENCES Spot(id) ON DELETE CASCADE
);