CREATE DATABASE IF NOT EXISTS `campfinderdb` DEFAULT CHARACTER SET utf8mb4 ;
USE `campfinderdb` ;

DROP TABLE IF EXISTS User CASCADE;
DROP TABLE IF EXISTS Spot CASCADE;
DROP TABLE IF EXISTS Comment CASCADE;
DROP TABLE IF EXISTS SpotImgURL CASCADE;

CREATE TABLE User (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,  -- 暗号化されたパスワードを格納
    is_admin BOOLEAN DEFAULT FALSE
);

CREATE TABLE Spot (
    id SERIAL PRIMARY KEY,
    category VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    period VARCHAR(150) DEFAULT '-',
    phone VARCHAR(100) DEFAULT '-',
    price VARCHAR(400) DEFAULT '-',
    description TEXT DEFAULT '-',
    iconpath VARCHAR(30) DEFAULT 'iconpath'
);

CREATE TABLE Comment (
    id SERIAL PRIMARY KEY,
    spot_id INTEGER NOT NULL REFERENCES Spot(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
    star_rate DECIMAL(2,1) NOT NULL,
    text TEXT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SpotImgURL (
    id SERIAL PRIMARY KEY,
    spot_id INTEGER NOT NULL REFERENCES Spot(id) ON DELETE CASCADE,
    url VARCHAR(200)
)