// Code generated by MockGen. DO NOT EDIT.
// Source: spot.go

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSpotHandler is a mock of SpotHandler interface.
type MockSpotHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSpotHandlerMockRecorder
}

// MockSpotHandlerMockRecorder is the mock recorder for MockSpotHandler.
type MockSpotHandlerMockRecorder struct {
	mock *MockSpotHandler
}

// NewMockSpotHandler creates a new mock instance.
func NewMockSpotHandler(ctrl *gomock.Controller) *MockSpotHandler {
	mock := &MockSpotHandler{ctrl: ctrl}
	mock.recorder = &MockSpotHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotHandler) EXPECT() *MockSpotHandlerMockRecorder {
	return m.recorder
}

// HandleSpotCreate mocks base method.
func (m *MockSpotHandler) HandleSpotCreate(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSpotCreate", w, r)
}

// HandleSpotCreate indicates an expected call of HandleSpotCreate.
func (mr *MockSpotHandlerMockRecorder) HandleSpotCreate(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSpotCreate", reflect.TypeOf((*MockSpotHandler)(nil).HandleSpotCreate), w, r)
}

// HandleSpotGet mocks base method.
func (m *MockSpotHandler) HandleSpotGet(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSpotGet", w, r)
}

// HandleSpotGet indicates an expected call of HandleSpotGet.
func (mr *MockSpotHandlerMockRecorder) HandleSpotGet(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSpotGet", reflect.TypeOf((*MockSpotHandler)(nil).HandleSpotGet), w, r)
}
