USE `campfinderdb` ;

DROP TABLE IF EXISTS TestItems CASCADE;

CREATE TABLE TestItems (
    id CHAR(36) PRIMARY KEY, -- UUIDは36文字の文字列として格納されます
    user_id CHAR(36) NOT NULL,
    text TEXT NOT NULL,
    count INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
