
name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches-ignore:
      - main
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.2

      - name: Setup .certificate directory
        run: mkdir -p .certificate

      - name: Create Private Key
        run: echo "${{ secrets.PRIVATE_KEY }}" > .certificate/private_key.pem
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        id: setup-go
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum

      - name: Download Go modules
        shell: bash
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        run: |
          go mod download
          go mod verify

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: rm -rf .certificate