
name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches-ignore:
      - main
  pull_request:
    branches: [ "develop" ]
  workflow_call:
    secrets:
      PRIVATE_KEY:
        required: true
      PUBLIC_KEY:
        required: true
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker/back/
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.2

      - name: Create Private and Public Keys
        run: |
          mkdir -p .certificate
          echo "${{ secrets.PRIVATE_KEY }}" > .certificate/private_key.pem
          echo "${{ secrets.PUBLIC_KEY }}" > .certificate/public_key.pem
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        id: setup-go
        with:
          go-version-file: ./docker/back//go.mod
          cache-dependency-path: ./docker/back//go.sum

      - name: Download Go modules
        shell: bash
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        run: |
          go mod download
          go mod verify

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: Lint
        run: golangci-lint run

      - name: Cleanup
        if: always()
        run: rm -rf .certificate